[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "v$version"
version_files = [
    ".cz.toml:version",
    "app/main.py:version"
]
update_changelog_on_bump = true
major_version_zero = true
